steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim' 
  args:
  - gcloud
  - functions
  - deploy
  - function_cid
  - --region==us-central1
  - --source==.
  - --trigger-http
  - --runtime==python310
  - --allow-unauthenticated
