steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk' 
  args:
  - gcloud
  - functions
  - deploy
  - function_cicd
  - --region=us-central1
  - --source=.
  - --trigger-http
  - --runtime=python310
  - --allow-unauthenticated
options:
  logging: CLOUD_LOGGING_ONLY
  logStreamingOption: STREAM_ON
  substitution_option: 'ALLOW_LOOSE'
timeout: 1600s
