serviceAccount: 'projects/gcp-devops-435917/serviceAccounts/cicd-sa@gcp-devops-435917.iam.gserviceaccount.com'
steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -x
    gcloud config list
    gcloud functions deploy function_cicd \
      --region=us-central1 \
      --source=. \
      --trigger-http \
      --runtime=python310 \
      --allow-unauthenticated \
      --set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID
options:
  logging: CLOUD_LOGGING_ONLY
  logStreamingOption: STREAM_ON
