steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -x
    echo "Current working directory: $(pwd)"
    echo "Contents of current directory:"
    ls -la
    echo "Environment variables:"
    env
    echo "gcloud config list:"
    gcloud config list
    echo "Attempting to deploy function:"
    gcloud functions deploy function_cicd \
      --region=us-central1 \
      --source=. \
      --trigger-http \
      --runtime=python310 \
      --allow-unauthenticated \
      --set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID
options:
  logging: CLOUD_LOGGING_ONLY
  logStreamingOption: STREAM_ON
